# Generated by Django 5.0.6 on 2024-07-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('text', models.TextField(max_length=140, verbose_name='本文')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/', verbose_name='画像（空欄可）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
